import Foundation

@MainActor
final class LanguageManager: ObservableObject {
    static let shared = LanguageManager()

    @Published var currentLanguage: Language {
        didSet {
            UserDefaults.standard.set(currentLanguage.rawValue, forKey: "di-quest-lang")
        }
    }

    enum Language: String, CaseIterable {
        case zhTW = "zh-TW"
        case en = "en"

        var displayName: String {
            switch self {
            case .zhTW: return "繁體中文"
            case .en: return "English"
            }
        }

        var shortName: String {
            switch self {
            case .zhTW: return "中"
            case .en: return "EN"
            }
        }
    }

    private init() {
        let saved = UserDefaults.standard.string(forKey: "di-quest-lang") ?? "zh-TW"
        self.currentLanguage = Language(rawValue: saved) ?? .zhTW
    }

    var isEnglish: Bool { currentLanguage == .en }

    func toggle() {
        currentLanguage = isEnglish ? .zhTW : .en
    }

    // MARK: - Localized UI Strings

    func string(_ key: String) -> String {
        return strings[key] ?? key
    }

    private var strings: [String: String] {
        isEnglish ? enStrings : zhStrings
    }

    private let zhStrings: [String: String] = [
        "app.subtitle": "Case Study 面試練習",
        "tab.explore": "探索",
        "tab.progress": "進度",
        "tab.chat": "小迪",
        "tab.social": "社群",
        "tab.review": "複習",
        "action.startChallenge": "開始挑戰",
        "action.continueChallenge": "繼續挑戰",
        "action.readLesson": "閱讀講義",
        "action.startReading": "開始閱讀",
        "action.submit": "確認答案",
        "action.next": "下一題",
        "action.done": "完成",
        "action.signOut": "登出",
        "action.settings": "設定",
        "lesson.toc": "目錄",
        "lesson.notFound": "找不到這個世界的講義",
        "quest.detail": "任務詳情",
        "quest.complete": "任務完成！",
        "quest.xp": "XP",
        "quest.challenges": "挑戰",
        "quest.completed": "完成",
        "challenge.correct": "答對了！",
        "challenge.wrong": "答錯了",
        "challenge.hint": "提示",
        "challenge.showNextHint": "顯示下一個提示",
        "challenge.alreadyCompleted": "已完成",
        "progress.title": "進度",
        "progress.streak": "連續天數",
        "progress.longestStreak": "最長連續",
        "progress.questsDone": "已完成任務",
        "progress.challengesDone": "已完成挑戰",
        "progress.dailyCheckin": "每日簽到",
        "progress.checkedIn": "今日已簽到",
        "chat.title": "小迪",
        "chat.placeholder": "問小迪任何問題...",
        "chat.greeting": "嗨！我是小迪 👋 你的面試練習教練。有什麼我可以幫你的嗎？",
        "chat.error": "抱歉，我暫時無法連接 AI 服務。你可以試試問我特定的分析概念！",
        "chat.rateLimit": "今日已達上限（每天 20 次）",
        "settings.title": "設定",
        "settings.about": "關於",
        "settings.version": "版本",
        "settings.security": "安全性",
        "settings.storage": "儲存空間",
        "settings.cacheSize": "快取大小",
        "settings.clearCache": "清除快取",
        "settings.account": "帳號",
        "settings.language": "語言",
        "settings.languageFooter": "切換介面和內容語言",
        "branch.worlds": "個世界",
        "social.comingSoon": "社群功能即將推出",
        "review.comingSoon": "複習系統即將推出",
        // Auth
        "auth.enterEmailPassword": "請輸入 Email 和密碼",
        "auth.signInFailed": "登入失敗",
        "auth.signUpFailed": "註冊失敗",
        "auth.passwordMinLength": "密碼至少需要 6 個字元",
        "auth.verificationSent": "已發送驗證信到你的信箱，請先驗證後再登入",
        "auth.unknownError": "發生未知錯誤",
        "auth.enterEmail": "請輸入 Email",
        "auth.resetSent": "已發送密碼重設信到",
        "auth.resetFailed": "發送失敗，請確認 Email 是否正確",
        "auth.sendFailed": "發送失敗",
        "auth.signUp": "註冊",
        "auth.signIn": "登入",
        "auth.hasAccount": "已有帳號？",
        "auth.noAccount": "還沒有帳號？",
        "auth.forgotPassword": "忘記密碼？",
        "auth.or": "或",
        "auth.signInWithGoogle": "使用 Google 登入",
        "auth.signInWithApple": "使用 Apple 登入",
        "auth.password": "密碼",
        "auth.resetEmailSent": "已發送重設信",
        "auth.resetPassword": "重設密碼",
        "auth.checkInbox": "請查看你的信箱並點擊連結重設密碼",
        "auth.enterEmailForReset": "輸入你的 Email，我們會寄送密碼重設連結",
        "auth.sendResetLink": "發送重設連結",
        "auth.close": "關閉",
        // Challenge types
        "challenge.multipleChoice": "選擇題",
        "challenge.openEnded": "開放題",
        "challenge.code": "程式題",
        "challenge.title": "挑戰",
        "quest.continue": "繼續",
        // Settings extra
        "settings.biometric": "生物辨識",
        "settings.requireBiometric": "開啟 App 時需要%@驗證",
        "settings.promoCode": "兌換碼",
        "settings.enterPromoCode": "輸入兌換碼",
        "settings.redeem": "兌換",
        "settings.promoFooter": "輸入兌換碼解鎖進階內容",
        "settings.clearCacheConfirm": "確定要清除快取？",
        "settings.cancel": "取消",
        "settings.clearCacheMessage": "這會清除所有離線快取資料",
        "settings.signOutConfirm": "確定要登出？",
        "settings.loginFirst": "請先登入",
        "settings.serverError": "伺服器錯誤",
        "settings.parseError": "解析錯誤",
        "settings.invalidCode": "無效的兌換碼",
        "settings.codeExpired": "此兌換碼已過期",
        "settings.redeemFailed": "兌換失敗",
        "settings.premiumActivated": "進階版已啟用！所有內容已解鎖。",
        "settings.error": "錯誤",
        // Progress
        "progress.branchProgress": "路線進度",
        "progress.achievements": "成就",
        "progress.last7Days": "近 7 天",
        "progress.noActivity": "尚無活動記錄",
        "progress.checkinComplete": "簽到成功！",
        "progress.dailyCheckinTitle": "每日簽到",
        "progress.xpEarned": "XP 已獲得！",
        "progress.claimReward": "領取每日獎勵",
        "progress.dayStreak": "連續天數",
        "progress.bestStreak": "最長紀錄",
        "progress.claimXp": "領取獎勵",
        "progress.dailyGoal": "每日目標",
        "progress.dailyGoalDone": "今日目標已達成！",
        "progress.dailyGoalRemaining": "距離今日目標還需更多 XP",
        "progress.streakFreezeAvailable": "連續紀錄保護可用",
        "progress.streakFreezeNone": "沒有連續紀錄保護",
        // Chat
        "chat.explainConcept": "解釋概念",
        "chat.explainConceptMsg": "可以解釋什麼是 funnel analysis 嗎？",
        "chat.imStuck": "我卡住了",
        "chat.imStuckMsg": "我卡在一個挑戰上，可以給我一些提示嗎？",
        "chat.interviewTips": "面試建議",
        "chat.interviewTipsMsg": "Case study 面試有什麼建議嗎？",
        "chat.myProgress": "我的進度",
        "chat.myProgressMsg": "我的學習進度如何？",
        "chat.noChatHistory": "沒有聊天記錄",
        "chat.newChat": "新對話",
        "chat.chatHistory": "聊天記錄",
        "chat.botName": "小迪",
        // Social
        "social.friends": "好友",
        "social.requests": "邀請",
        "social.ranking": "排行榜",
        "social.alreadyFriends": "你們已經是好友了！",
        "social.linkCopied": "已複製連結！",
        "social.shareMessage": "來 DI Quest 一起練習 Case Study 面試吧！",
        "social.searchPlaceholder": "搜尋用戶名稱...",
        "social.searchResults": "搜尋結果",
        "social.myFriends": "我的好友",
        "social.noFriends": "還沒有好友",
        "social.searchToAdd": "搜尋用戶名稱來加好友",
        "social.noPending": "沒有待處理的邀請",
        "social.noRankings": "尚無排行",
        "social.inviteFriends": "邀請好友",
        "social.shareLink": "分享連結邀請好友一起學習",
        "social.copyLink": "複製邀請連結",
        "social.requestSent": "好友邀請已送出！",
        "social.requestAlready": "邀請已送出過",
        "social.requestFailed": "無法送出邀請",
        "social.wantsFriend": "想加你為好友",
        // Review
        "review.allCaughtUp": "全部複習完畢！",
        "review.noDue": "目前沒有需要複習的挑戰。\n完成更多挑戰來建立複習佇列。",
        "review.inSystem": "系統中",
        "review.nextReview": "下次複習",
        "review.dueForReview": "題待複習",
        "review.tapToReview": "點擊挑戰開始複習",
        "review.none": "無",
        "review.now": "現在",
        "review.days": "天",
        // Cache
        "cache.calculating": "計算中...",
        // Supabase
        "error.requestFailed": "伺服器請求失敗",
        // Calendar
        "calendar.title": "活動日曆",
        // Analytics
        "analytics.title": "深入分析",
        "analytics.dailyActivity": "每日挑戰 (14 天)",
        "analytics.xpTrend": "每日 XP (14 天)",
        "analytics.avgTime": "每世界平均答題時間",
        "analytics.seconds": "秒",
        "analytics.noData": "尚無資料",
        // Search
        "search.title": "搜尋",
        "search.placeholder": "搜尋世界、任務、挑戰...",
        "search.worlds": "世界",
        "search.quests": "任務",
        "search.challenges": "挑戰",
        "search.noResults": "找不到結果",
        // Code Editor
        "code.placeholder": "在此輸入 SQL 查詢...",
        "code.expectedOutput": "查看預期結果",
        "code.submitted": "已提交！",
        "code.referenceAnswer": "參考答案",
        "code.lines": "行",
        "code.schema": "資料表結構",
        // Open-ended
        "openEnded.placeholder": "在此輸入你的回答...（至少 20 字）",
        "openEnded.submit": "提交評估",
        "openEnded.evaluating": "AI 評估中...",
        "openEnded.score": "分數",
        "openEnded.strengths": "優點",
        "openEnded.improvements": "改進建議",
        "openEnded.reference": "參考方向",
        "openEnded.retry": "重新作答",
        "openEnded.passed": "通過！",
        "openEnded.failed": "未通過，請再試試",
        "openEnded.minChars": "至少需要 20 個字元",
        "openEnded.apiLimit": "今日 AI 評估次數已達上限",
    ]

    private let enStrings: [String: String] = [
        "app.subtitle": "Case Study Interview Prep",
        "tab.explore": "Explore",
        "tab.progress": "Progress",
        "tab.chat": "Dash",
        "tab.social": "Social",
        "tab.review": "Review",
        "action.startChallenge": "Start Challenge",
        "action.continueChallenge": "Continue",
        "action.readLesson": "Read Lesson",
        "action.startReading": "Start Reading",
        "action.submit": "Submit",
        "action.next": "Next",
        "action.done": "Done",
        "action.signOut": "Sign Out",
        "action.settings": "Settings",
        "lesson.toc": "Contents",
        "lesson.notFound": "Lesson not found for this world",
        "quest.detail": "Quest Detail",
        "quest.complete": "Quest Complete!",
        "quest.xp": "XP",
        "quest.challenges": "Challenges",
        "quest.completed": "Done",
        "challenge.correct": "Correct!",
        "challenge.wrong": "Incorrect",
        "challenge.hint": "Hints",
        "challenge.showNextHint": "Show next hint",
        "challenge.alreadyCompleted": "Completed",
        "progress.title": "Progress",
        "progress.streak": "Streak",
        "progress.longestStreak": "Best Streak",
        "progress.questsDone": "Quests Done",
        "progress.challengesDone": "Challenges Done",
        "progress.dailyCheckin": "Daily Check-in",
        "progress.checkedIn": "Checked in today",
        "chat.title": "Dash",
        "chat.placeholder": "Ask Dash anything...",
        "chat.greeting": "Hi! I'm Dash 👋 Your interview practice coach. How can I help?",
        "chat.error": "Sorry, I can't connect to the AI service right now. Try asking about specific concepts!",
        "chat.rateLimit": "Daily limit reached (20 calls/day)",
        "settings.title": "Settings",
        "settings.about": "About",
        "settings.version": "Version",
        "settings.security": "Security",
        "settings.storage": "Storage",
        "settings.cacheSize": "Cache Size",
        "settings.clearCache": "Clear Cache",
        "settings.account": "Account",
        "settings.language": "Language",
        "settings.languageFooter": "Switch interface and content language",
        "branch.worlds": "worlds",
        "social.comingSoon": "Social features coming soon",
        "review.comingSoon": "Review system coming soon",
        // Auth
        "auth.enterEmailPassword": "Please enter email and password",
        "auth.signInFailed": "Sign in failed",
        "auth.signUpFailed": "Sign up failed",
        "auth.passwordMinLength": "Password must be at least 6 characters",
        "auth.verificationSent": "Verification email sent. Please verify before signing in.",
        "auth.unknownError": "An unknown error occurred",
        "auth.enterEmail": "Please enter your email",
        "auth.resetSent": "Password reset email sent to",
        "auth.resetFailed": "Failed to send. Please check your email.",
        "auth.sendFailed": "Failed to send",
        "auth.signUp": "Sign Up",
        "auth.signIn": "Sign In",
        "auth.hasAccount": "Already have an account?",
        "auth.noAccount": "Don't have an account?",
        "auth.forgotPassword": "Forgot password?",
        "auth.or": "or",
        "auth.signInWithGoogle": "Sign in with Google",
        "auth.signInWithApple": "Sign in with Apple",
        "auth.password": "Password",
        "auth.resetEmailSent": "Reset email sent",
        "auth.resetPassword": "Reset Password",
        "auth.checkInbox": "Check your inbox and click the link to reset your password",
        "auth.enterEmailForReset": "Enter your email and we'll send a password reset link",
        "auth.sendResetLink": "Send Reset Link",
        "auth.close": "Close",
        // Challenge types
        "challenge.multipleChoice": "Multiple Choice",
        "challenge.openEnded": "Open Ended",
        "challenge.code": "Code",
        "challenge.title": "Challenge",
        "quest.continue": "Continue",
        // Settings extra
        "settings.biometric": "Biometrics",
        "settings.requireBiometric": "Require %@ when opening app",
        "settings.promoCode": "Promo Code",
        "settings.enterPromoCode": "Enter code",
        "settings.redeem": "Redeem",
        "settings.promoFooter": "Enter a promo code to unlock premium content",
        "settings.clearCacheConfirm": "Clear cache?",
        "settings.cancel": "Cancel",
        "settings.clearCacheMessage": "This will clear all offline cached data",
        "settings.signOutConfirm": "Sign out?",
        "settings.loginFirst": "Please log in first",
        "settings.serverError": "Server error",
        "settings.parseError": "Parse error",
        "settings.invalidCode": "Invalid promo code",
        "settings.codeExpired": "This code has expired",
        "settings.redeemFailed": "Failed to apply code",
        "settings.premiumActivated": "Premium activated! All content unlocked.",
        "settings.error": "Error",
        // Progress
        "progress.branchProgress": "Branch Progress",
        "progress.achievements": "Achievements",
        "progress.last7Days": "Last 7 Days",
        "progress.noActivity": "No activity yet",
        "progress.checkinComplete": "Check-in Complete!",
        "progress.dailyCheckinTitle": "Daily Check-in",
        "progress.xpEarned": "XP earned!",
        "progress.claimReward": "Claim your daily reward",
        "progress.dayStreak": "Day Streak",
        "progress.bestStreak": "Best Streak",
        "progress.claimXp": "Claim Reward",
        "progress.dailyGoal": "Daily Goal",
        "progress.dailyGoalDone": "Daily goal achieved!",
        "progress.dailyGoalRemaining": "More XP needed to reach daily goal",
        "progress.streakFreezeAvailable": "Streak freeze available",
        "progress.streakFreezeNone": "No streak freeze available",
        // Chat
        "chat.explainConcept": "Explain a concept",
        "chat.explainConceptMsg": "Can you explain what a funnel analysis is?",
        "chat.imStuck": "I'm stuck",
        "chat.imStuckMsg": "I'm stuck on a challenge, can you give me some guidance?",
        "chat.interviewTips": "Interview tips",
        "chat.interviewTipsMsg": "What tips do you have for case study interviews?",
        "chat.myProgress": "My progress",
        "chat.myProgressMsg": "How am I doing with my learning progress?",
        "chat.noChatHistory": "No chat history",
        "chat.newChat": "New Chat",
        "chat.chatHistory": "Chat History",
        "chat.botName": "Dash",
        // Social
        "social.friends": "Friends",
        "social.requests": "Requests",
        "social.ranking": "Ranking",
        "social.alreadyFriends": "You are already friends!",
        "social.linkCopied": "Link copied!",
        "social.shareMessage": "Join me on DI Quest! Practice case study interviews together.",
        "social.searchPlaceholder": "Search by username...",
        "social.searchResults": "Search Results",
        "social.myFriends": "My Friends",
        "social.noFriends": "No friends yet",
        "social.searchToAdd": "Search for users to add friends",
        "social.noPending": "No pending requests",
        "social.noRankings": "No rankings yet",
        "social.inviteFriends": "Invite Friends",
        "social.shareLink": "Share your link to add friends",
        "social.copyLink": "Copy Invite Link",
        "social.requestSent": "Friend request sent!",
        "social.requestAlready": "Request already sent",
        "social.requestFailed": "Could not send request",
        "social.wantsFriend": "wants to be your friend",
        // Review
        "review.allCaughtUp": "All caught up!",
        "review.noDue": "No challenges due for review.\nComplete more challenges to build your review queue.",
        "review.inSystem": "In System",
        "review.nextReview": "Next Review",
        "review.dueForReview": "due for review",
        "review.tapToReview": "Tap a challenge to review it",
        "review.none": "None",
        "review.now": "Now",
        "review.days": "d",
        // Cache
        "cache.calculating": "Calculating...",
        // Supabase
        "error.requestFailed": "Server request failed",
        // Calendar
        "calendar.title": "Activity Calendar",
        // Analytics
        "analytics.title": "Analytics",
        "analytics.dailyActivity": "Daily Challenges (14 days)",
        "analytics.xpTrend": "Daily XP (14 days)",
        "analytics.avgTime": "Avg Time per World",
        "analytics.seconds": "sec",
        "analytics.noData": "No data yet",
        // Search
        "search.title": "Search",
        "search.placeholder": "Search worlds, quests, challenges...",
        "search.worlds": "Worlds",
        "search.quests": "Quests",
        "search.challenges": "Challenges",
        "search.noResults": "No results found",
        // Code Editor
        "code.placeholder": "Write your SQL query here...",
        "code.expectedOutput": "View Expected Output",
        "code.submitted": "Submitted!",
        "code.referenceAnswer": "Reference Answer",
        "code.lines": "lines",
        "code.schema": "Table Schema",
        // Open-ended
        "openEnded.placeholder": "Type your answer here... (min 20 characters)",
        "openEnded.submit": "Submit for Evaluation",
        "openEnded.evaluating": "AI is evaluating...",
        "openEnded.score": "Score",
        "openEnded.strengths": "Strengths",
        "openEnded.improvements": "Suggestions for Improvement",
        "openEnded.reference": "Reference Direction",
        "openEnded.retry": "Try Again",
        "openEnded.passed": "Passed!",
        "openEnded.failed": "Not yet passed, try again",
        "openEnded.minChars": "At least 20 characters required",
        "openEnded.apiLimit": "Daily AI evaluation limit reached",
    ]
}
